name: firstworkflow
on: push

jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Run test
        run: npm test

      - name: Npm Build
        run: npm run build

  
